### ISSUE TITLE
minor issue with link on hub.docker

### ISSUE THREAD

**Issue by cybermcm** [pitkley/dfw#131]
Hi,

Readme on hub.docker.com points to https://hub.docker.com/r/pitkley/MIGRATION-v0.x-to-v1.0.md but instead should point to https://github.com/pitkley/dfw/blob/master/MIGRATION-v0.x-to-v1.0.md

**Comment by pitkley** [comment]
Hm... it is unfortunate that the Docker Hub auto-readme feature isn't smart enough to turn relative GitHub-links into absolute ones. I'll replace them in the GitHub readme which should fix the Docker Hub readme. 👍
