### ISSUE TITLE
dfw:iptables currently broken

### ISSUE THREAD

**Issue by cybermcm** [pitkley/dfw#177]
using latest:iptables (https://www.github.com/pitkley/dfw/tree/198799591d1c930a9465e321a754e9e8744ee944)
log shows:
`thread 'main' panicked at 'Specifier `%Y` requires a date to be present.', src/libcore/option.rs:1185:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.`
repeating....

**Comment by pitkley** [comment]
Oops, thanks for noticing. I have pushed a fix, Docker Hub is building the new tag right now. Please let me know if that solves your issue!

**Comment by cybermcm** [comment]
perfect, running fine again with dfw:iptables (https://www.github.com/pitkley/dfw/tree/3fc52aa398a9cf7bd828c1a91c630e800505bf68)
thanks
