### ISSUE TITLE
Potentially use bollard instead of shiplift

### ISSUE THREAD

**Issue by pitkley** [pitkley/dfw#286]
[bollard](https://github.com/fussybeaver/bollard) seems to be a modern, maybe more up-to-date alternative to shiplift. Specifically it is updated to the latest tokio/futures/hyper releases, which would pave the way for potentially using async/await in the future (although we have no direct benefit from this).

**Comment by pitkley** [comment]
One potential problem: currently [bollard is pinned to Docker API version `1.40`])https://github.com/fussybeaver/bollard/tree/8ba2595fff5f69c1aa72ef501420230363b74a50#version_, which has only been available [since Docker version `19.03.0`](https://docs.docker.com/engine/release-notes/#19030). We need to make sure that we don't break older Docker versions.

**Comment by fussybeaver** [comment]
Bollard also has version negotiation, like the go client https://docs.rs/bollard/0.6.1/bollard/struct.Docker.html#method.negotiate_version

Let me know if have any questions or get blocked on any features you may need..

**Comment by pitkley** [comment]
@fussybeaver thank you so much for reaching out! That is very interesting and probably covers what I need perfectly.

I'm not sure when I'll get around to replacing shiplift (and I still haven't ultimately decided if I will, since I'm not experiencing any issues with it), but if I reach any blockers I will get back to you! :+1:
