### ISSUE TITLE
Possible to limit acces to container from www by ip?

### ISSUE THREAD

**Issue by Yaikava** [pitkley/dfw#587]
For example: I wanna allow only one ip to be able to access my database.

**Comment by pitkley** [comment]
Given that you have closed this issue I assume you were able to solve this. In case you weren't, or anyone else comes across this ticket: this is possible, yes. You can provide the `source_cidr_v{4,6}` fields in your wider-world-to-container rule. More details on this can be found:

* In the configuration reference: <https://dfw.rs/latest/dfw/types/struct.WiderWorldToContainerRule.html#structfield.source_cidr_v4>.
* In one of the configurations that is used for automatic testing: <https://github.com/pitkley/dfw/blob/2c1f2838a4825231f6dc6f86a750f712233e7fde/resources/test/docker/05/conf.toml#L26-L38>.
